version: '3'

services:

  frontend:
    labels:
      shipyard.route: '/'
    build: 'frontend'
    volumes:
      - './frontend/src:/srv/src'
    ports:
      - '8080:8080'
  
  backend:
    labels:
      shipyard.route: '/graphql'
    build: 'backend'
    command: yarn start
    volumes:
      - ./backend/src/:/app/src/
    environment:
      - PORT=3000
      - DATABASE=wishlist
      - DATABASE_USER=wishlist
      - DATABASE_PASSWORD=wishlist
      - DATABASE_HOST=postgres
      - NODE_ENV=development
    ports:
      - '3000'
    depends_on:
      - postgres

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: 'wishlist'
      POSTGRES_USER: 'wishlist'
      POSTGRES_PASSWORD: 'wishlist'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  postgres:
